### ISSUE TITLE
Add zurb foundation 5.x support

### ISSUE THREAD

**Issue by cananda** [awestruct/awestruct#418]
Just curious if there are plans to add foundation 5.x support is on the radar?

**Comment by akostadinov** [comment]
There is foundation 6 now. Any plans to support that? Any workaround so one can use it instead of zurb-foundation 4?

**Comment by akostadinov** [comment]
There is foundation 6 now. Any plans to support that? Any workaround so one can use it instead of zurb-foundation 4? 

I see a couple of dynamic installation methods listed here:
http://foundation.zurb.com/sites/docs/

Since it is SCSS it should not be so hard to integrate with. Unfortunately I'm just starting to look at web page frontend development and have little idea what foundation is, even less how to integrate.

**Comment by zbynek** [comment]
Closing this in favor of #525
